[build]
builder = "nixpacks"

[deploy]
startCommand = "cd api && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
PORT = "3001"

[[services]]
name = "lingua-stagify-api"
source = "."
